name: Create Release Pull Request
on:
  push:
    branches:
      - main
      - release/stg
  
permissions:
  contents: read
  pull-requests: write


jobs:
  create-release-pr-stg:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'main')
    steps:
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - run: mise use -g github:odanado/git-pr-release-go

      - run: git-pr-release-go -help

      - run: git-pr-release-go --from main --to release/stg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-release-pr-prod:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'release/stg')
    steps:
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - run: mise use -g github:odanado/git-pr-release-go

      - run: git-pr-release-go -help

      - run: git-pr-release-go --from release/stg --to release/prod
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
