name: Create Release Pull Request
on:
  push:
    branches:
      - main

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - run: mise use -g github:odanado/git-pr-release-go

      - run: git-pr-release-go -help

      # - run: git-pr-release-go --from main --to release/production
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
